--------------------------------------------------------
-- Archivo creado  - jueves-marzo-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPARTO
--------------------------------------------------------

  CREATE TABLE "DESAFIO2"."REPARTO" 
   (	"IDPELICULA" VARCHAR2(100 BYTE), 
	"NOMBREACTOR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DESAFIO2.REPARTO
SET DEFINE OFF;
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Avery Brooks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Beverly D''Angelo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Jennifer Lien');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Guy Torry');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Ethan Suplee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('20','Keram Malicki-Sanchez');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Gerard Butler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Lena Headey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','David Wenham');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Dominic West');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Vincent Regan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Rodrigo Santoro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Michael Fassbender');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Andrew Tieman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Andrew Pleavin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Tom Wisdom');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Tim Conolly');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Tyler Max Neitzel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Mercedes Leggett');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('21','Peter Mensah');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Bruce Willis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Toni Collette');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Haley Joel Osment');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Olivia Williams');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Trevor Morgan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Donnie Wahlberg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Peter Tambakis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Jeffrey Zubernis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','Bruce Norris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('22','KaDee Strickland');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','John Travolta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Uma Thurman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Bruce Willis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Harvey Keitel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Eric Stoltz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Tim Roth');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Maria de Medeiros');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Amanda Plummer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Ving Rhames');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Rosanna Arquette');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Christopher Walken');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Quentin Tarantino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Peter Greene');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('23','Phil LaMarr');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Natalie Portman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Hugo Weaving');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Stephen Rea');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','John Hurt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Stephen Fry');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Rupert Graves');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Tim Pigott-Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Roger Allam');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Ben Miles');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Sinead Cusack');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Natasha Wightman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Eddie Marsan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('24','Billie Cook');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Jodie Foster');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Anthony Hopkins');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Scott Glenn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Ted Levine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Anthony Heald');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Diane Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Brooke Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Tracey Walter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Kasi Lemmons');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Chris Isaak');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Roger Corman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Frankie Faison');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('25','Paul Lazar');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Sylvester Stallone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Talia Shire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Burt Young');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Carl Weathers');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Burgess Meredith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Thayer David');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('26','Joe Spinell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Brad Pitt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Edward Norton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Helena Bonham Carter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Meat Loaf');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Jared Leto');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Van Quattro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Markus Redmond');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Michael Girardin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Rachel Singer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('27','Eion Bailey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Henry Thomas');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Dee Wallace');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Robert MacNaughton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Drew Barrymore');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Peter Coyote');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','C. Thomas Howell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','K.C. Martel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Sean Frye');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('28','Erika Eleniak');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Sam Neill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Laura Dern');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Jeff Goldblum');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Richard Attenborough');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Ariana Richards');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Joseph Mazzello');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Wayne Knight');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Bob Peck');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','Martin Ferrero');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('29','B.D. Wong');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Keanu Reeves');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Laurence Fishburne');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Carrie-Anne Moss');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Hugo Weaving');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Joe Pantoliano');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Marcus Chong');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Paul Goddard');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('30','Gloria Foster');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Tom Hanks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Michael Clarke Duncan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','David Morse');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Michael Jeter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Doug Hutchison');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Sam Rockwell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Barry Pepper');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Jeffrey DeMunn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Bonnie Hunt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','James Cromwell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Graham Greene');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Gary Sinise');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Harry Dean Stanton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Patricia Clarkson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','William Sadler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('31','Paula Malcomson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('32','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','John Travolta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Olivia Newton-John');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Stockard Channing');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Jeff Conaway');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Didi Conn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Lorenzo Lamas');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Dinah Manoff');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Barry Pearl');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('33','Michael Tucci');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Al Pacino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Robert De Niro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Diane Keaton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Robert Duvall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','James Caan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','John Cazale');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Lee Strasberg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Talia Shire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Marianna Hill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Danny Aiello');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Harry Dean Stanton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Troy Donahue');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Roger Corman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('34','Morgana King');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('35','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Robert Downey Jr.');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Terrence Howard');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Gwyneth Paltrow');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Jeff Bridges');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Stan Lee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Leslie Bibb');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Clark Gregg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Shaun Toub');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Faran Tahir');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('36','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Linda Blair');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Max von Sydow');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Ellen Burstyn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Jason Miller');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Lee J. Cobb');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Kitty Winn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Jack MacGowran');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Arthur Storch');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Barton Heyman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('37','Gina Petrushka');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Johnny Depp');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Orlando Bloom');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Keira Knightley');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Stellan Skarsgård');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Bill Nighy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Naomie Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Jonathan Pryce');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Jack Davenport');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Lee Arenberg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Mackenzie Crook');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Kevin McNally');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('38','Geoffrey Rush');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Brad Pitt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Morgan Freeman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Gwyneth Paltrow');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Kevin Spacey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','John C. McGinley');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Richard Roundtree');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','R. Lee Ermey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Leland Orser');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('39','Richard Schiff');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Arnold Schwarzenegger');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Linda Hamilton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Edward Furlong');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Robert Patrick');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Earl Boen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Joe Morton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('40','Jenette Goldstein');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Jack Nicholson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Shelley Duvall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Danny Lloyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Scatman Crothers');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Barry Nelson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Philip Stone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Joe Turkel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Lia Beldman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Billie Gibson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Barry Denne');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','David Baxt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Manning Redwood');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Kisa Burns');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Louise Burns');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Alison Coleridge');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('41','Norman Gay');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Tommy Lee Jones');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Will Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Linda Fiorentino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Vincent D''Onofrio');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Sergio Calderón');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Rip Torn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Siobhan Fallon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Tony Shalhoub');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('42','Verne Troyer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Tobey Maguire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Kirsten Dunst');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Willem Dafoe');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','James Franco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Rosemary Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Cliff Robertson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','J.K. Simmons');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Bruce Campbell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Bill Nunn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('43','Stan Lee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Michael J. Fox');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Christopher Lloyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Lea Thompson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Thomas F. Wilson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Elisabeth Shue');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Charles Fleischer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Joe Flaherty');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Harry Waters Jr.');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('44','Billy Zane');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Jim Carrey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Laura Linney');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Noah Emmerich');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Natascha McElhone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Ed Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Holland Taylor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('45','Paul Giamatti');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('46','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('47','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Mark Hamill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Carrie Fisher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Peter Cushing');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Alec Guinness');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','David Prowse');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Peter Mayhew');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Anthony Daniels');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Kenny Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Phil Brown');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Shelagh Fraser');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Alex McCrindle');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('48','Jack Purvis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Cary Elwes');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Leigh Whannell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Danny Glover');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Monica Potter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Dina Meyer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Tobin Bell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Shawnee Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Ken Leung');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Alexandra Bokyun Chun');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('49','Michael Emerson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Arnold Schwarzenegger');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Linda Hamilton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Michael Biehn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Paul Winfield');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Lance Henriksen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Rick Rossovich');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Bess Motta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Earl Boen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Dick Miller');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('50','Bill Paxton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Uma Thurman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Lucy Liu');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Daryl Hannah');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Vivica A. Fox');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Sonny Chiba');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Chiaki Kuriyama');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Michael Bowen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Julie Dreyfus');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Michael Parks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','David Carradine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('51','Michael Madsen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Vivien Leigh');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Clark Gable');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Olivia de Havilland');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Leslie Howard');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Hattie McDaniel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Thomas Mitchell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Barbara O''Neil');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Butterfly McQueen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Ona Munson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Ann Rutherford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('52','Evelyn Keyes');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Ivana Baquero');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Sergi López');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Maribel Verdú');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Doug Jones');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Ariadna Gil');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','�?lex Angulo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Federico Luppi');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Roger Casamajor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Fernando Tielve');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('53','Pepa Pedroche');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('54','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('55','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Al Pacino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Michelle Pfeiffer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Steven Bauer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Mary Elizabeth Mastrantonio');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Robert Loggia');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','F. Murray Abraham');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Miriam Colon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Harris Yulin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('56','Paul Shenar');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Naomi Watts');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Adrien Brody');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Jack Black');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Thomas Kretschmann');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Jamie Bell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Lobo Chan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Kyle Chandler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Colin Hanks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Evan Parke');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Andy Serkis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('57','Ray Woolf');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Charlton Heston');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Jack Hawkins');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Stephen Boyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Haya Harareet');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Hugh Griffith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Martha Scott');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Cathy O''Donnell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Sam Jaffe');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Frank Thring');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Terence Longdon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','George Relph');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','André Morell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('58','Finlay Currie');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Sean Connery');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Alison Doody');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Denholm Elliott');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','River Phoenix');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','John Rhys-Davies');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Julian Glover');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Bradley Gregg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('59','Andre Gregory');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Leonardo DiCaprio');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Matt Damon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Jack Nicholson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Mark Wahlberg');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Alec Baldwin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Martin Sheen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Ray Winstone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Vera Farmiga');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('60','Anthony Anderson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('61','Tom Cruise');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Brad Pitt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Christian Slater');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Antonio Banderas');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Stephen Rea');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Kirsten Dunst');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Domiziana Giordano');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Sara Stockbridge');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Thandie Newton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Christian Bale');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Liam Neeson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Katie Holmes');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Cillian Murphy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Michael Caine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Morgan Freeman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Gary Oldman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Ken Watanabe');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Tom Wilkinson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Rutger Hauer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Mark Boone Junior');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Linus Roache');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Rade Serbedzija');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Richard Brake');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Christine Adams');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('62','Jack Gleeson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Karen Allen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Paul Freeman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Ronald Lacey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','John Rhys-Davies');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Denholm Elliott');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Wolf Kahler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('63','Alfred Molina');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Ewan McGregor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Natalie Portman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Hayden Christensen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Ian McDiarmid');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Ahmed Best');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Anthony Daniels');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Frank Oz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Andrew Secombe');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Silas Carson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Kenny Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Christopher Lee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Jimmy Smits');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Peter Mayhew');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Keisha Castle-Hughes');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Trisha Noble');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Bruce Spence');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('64','Temuera Morrison');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Sigourney Weaver');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','John Hurt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Yaphet Kotto');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Tom Skerritt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Veronica Cartwright');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Harry Dean Stanton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('65','Ian Holm');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Clint Eastwood');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Lee Van Cleef');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Eli Wallach');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Aldo Giuffrè');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Mario Brega');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Luigi Scarchilli');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('66','Rada Rassimov');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Mark Hamill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Carrie Fisher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Alec Guinness');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Billy Dee Williams');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Anthony Daniels');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','David Prowse');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('67','Kenny Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Al Pacino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Diane Keaton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Andy García');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Joe Mantegna');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Talia Shire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Eli Wallach');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Sofia Coppola');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','George Hamilton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Raf Vallone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Bridget Fonda');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Helmut Berger');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','John Savage');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('68','Franco Citti');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Mark Hamill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Carrie Fisher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Billy Dee Williams');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Anthony Daniels');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Peter Mayhew');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Frank Oz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Alec Guinness');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Kenny Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Sebastian Shaw');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Warwick Davis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('69','Dave Prowse');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Jack Black');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Joan Cusack');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Mike White');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Sarah Silverman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Joey Gaydos');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Miranda Cosgrove');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Maryam Hassan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Kevin Alexander Clark');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Rebecca Brown');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Robert Tsai');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Caitlin Hale');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Aleisha Allen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Brian Falduto');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Zachary Infante');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','James Hosey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Angelo Massagli');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Cole Hawkins');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('70','Veronica Afflerbach');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','Charlton Heston');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','Roddy McDowall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','Kim Hunter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','Maurice Evans');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','James Whitmore');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','James Daly');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('71','Linda Harrison');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Sylvester Stallone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Richard Crenna');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Brian Dennehy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','David Caruso');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Jack Starrett');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Michael Talbott');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('72','Chris Mulkey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Matthew Modine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Vincent D''Onofrio');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','R. Lee Ermey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Adam Baldwin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Dorian Harewood');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Arliss Howard');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Kevyn Major Howard');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Ed O''Ross');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Gary Landon Mills');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Sal López');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','John Stafford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Kieron Jecchinis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Ngc Le');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('73','Papillon Soo Soo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Roy Scheider');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Robert Shaw');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Richard Dreyfuss');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Lorraine Gary');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Murray Hamilton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Carl Gottlieb');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('74','Jeffrey C. Kramer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Jean Reno');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Natalie Portman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Gary Oldman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Danny Aiello');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Samy Nacery');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Peter Apple');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Michael Badalucco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Ellen Greene');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Elizabeth Regen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('75','Maïwenn Le Besco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Kevin Spacey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Annette Bening');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Thora Birch');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Allison Janney');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Peter Gallagher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Mena Suvari');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Wes Bentley');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Chris Cooper');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Scott Bakula');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Sam Robards');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('76','Barry Del Sherman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Humphrey Bogart');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Ingrid Bergman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Paul Henreid');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Claude Rains');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Conrad Veidt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Sydney Greenstreet');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Peter Lorre');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','S.Z. Sakall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Madeleine LeBeau');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Dooley Wilson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Joy Page');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','John Qualen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Leonid Kinskey');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('77','Curt Bois');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Audrey Tautou');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Mathieu Kassovitz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Rufus');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Lorella Cravotta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Serge Merlin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Jamel Debbouze');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Claire Maurier');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Clotilde Mollet');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Isabelle Nanty');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Dominique Pinon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Artus de Penguern');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Yolande Moreau');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Urbain Cancelier');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('78','Maurice Benichou');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Ewan McGregor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Robert Carlyle');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Jonny Lee Miller');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Ewen Bremner');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Kelly MacDonald');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Kevin McKidd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('79','Peter Mullan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Robert De Niro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Cybill Shepherd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Jodie Foster');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Albert Brooks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Harvey Keitel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Peter Boyle');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Leonard Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('80','Martin Scorsese');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Jack Nicholson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Louise Fletcher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','William Redfield');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Will Sampson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Brad Dourif');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Christopher Lloyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Danny DeVito');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('81','Scatman Crothers');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Uma Thurman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','David Carradine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Michael Madsen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Daryl Hannah');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Gordon Liu');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Michael Parks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Bo Svenson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Christopher Allen Nelson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Sid Haig');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('82','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Tobey Maguire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Kirsten Dunst');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Alfred Molina');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','James Franco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Elizabeth Banks');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Bruce Campbell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Rosemary Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','J.K. Simmons');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Vanessa Ferlito');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Emily Deschanel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('83','Stan Lee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Hugh Jackman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Patrick Stewart');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Brian Cox');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Ian McKellen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Halle Berry');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Anna Paquin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Famke Janssen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','James Marsden');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Rebecca Romijn-Stamos');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Alan Cumming');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Aaron Stanford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Shawn Ashmore');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Kelly Hu');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Bruce Davison');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Katie Stuart');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Kea Wong');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Cotter Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Bryce Hodgson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Shauna Kain');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Ty Olsson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Daniel Cudmore');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','James Kirk');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Jill Teed');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('84','Alf Humphreys');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Shia LaBeouf');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Megan Fox');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Jon Voight');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','John Turturro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Josh Duhamel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Tyrese Gibson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Bernie Mac');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Michael O''Neill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Julie White');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Rachael Taylor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Kevin Dunn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Amaury Nolasco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Ronnie Sperling');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('85','Anthony Anderson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Liam Neeson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Ewan McGregor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Natalie Portman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Jake Lloyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Ian McDiarmid');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Anthony Daniels');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Kenny Baker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Pernilla August');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Frank Oz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Ray Park');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Terence Stamp');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('86','Keira Knightley');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Sean Young');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Daryl Hannah');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Rutger Hauer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Edward James Olmos');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Joanna Cassidy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Brion James');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('87','Joe Turkel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Martin Sheen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Marlon Brando');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Robert Duvall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Laurence Fishburne');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Frederic Forrest');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Sam Bottoms');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Albert Hall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Dennis Hopper');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','G.D Spradlin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('88','Colleen Camp');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Jack Nicholson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Helen Hunt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Greg Kinnear');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Cuba Gooding Jr.');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Skeet Ulrich');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Shirley Knight');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Jesse James');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Lawrence Kasdan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Yeardley Smith');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Lupe Ontiveros');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Maya Rudolph');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Tara Subkoff');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Lisa Edelstein');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Jamie Kennedy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Harold Ramis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('89','Julie Benz');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','John Cleese');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Michael Palin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Graham Chapman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Eric Idle');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Terry Jones');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Terry Gilliam');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Sue Jones-Davies');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Carol Cleveland');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('90','Terence Bayler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('91','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Bill Murray');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Sigourney Weaver');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Dan Aykroyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Harold Ramis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Rick Moranis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','William Atherton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Annie Potts');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Ernie Hudson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('92','Reginald VelJohnson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('93','Johnny Depp');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('93','Helena Bonham Carter');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('93','Sacha Baron Cohen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('93','Alan Rickman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('93','Timothy Spall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','George Clooney');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Julia Roberts');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Matt Damon');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Andy García');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Brad Pitt');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Casey Affleck');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Scott Caan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Elliott Gould');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Bernie Mac');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Carl Reiner');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Don Cheadle');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Topher Grace');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Joshua Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Holly Marie Combs');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('94','Shane West');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('95','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Arnold Schwarzenegger');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Carl Weathers');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Elpidia Carrillo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Bill Duke');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Kevin Peter Hall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','Sonny Landham');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('96','R.G. Armstrong');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Harrison Ford');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Kate Capshaw');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Jonathan Ke Quan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Amrish Puri');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Philip Stone');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Roshan Seth');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','David Yip');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('97','Ric Young');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Robert De Niro');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Ray Liotta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Joe Pesci');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Lorraine Bracco');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Samuel L. Jackson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Paul Sorvino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Debi Mazar');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Mike Starr');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Tony Darrow');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Frank Sivero');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Frank Vincent');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Chuck Low');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Frank DiLeo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Clem Caserta');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Illeana Douglas');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Melissa Prophet');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Michael Imperioli');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('98','Tobin Bell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Nicole Kidman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Ewan McGregor');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','John Leguizamo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Jim Broadbent');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Richard Roxburgh');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','David Wenham');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Jacek Koman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('99','Kylie Minogue');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Anthony Perkins');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Janet Leigh');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','John Gavin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Vera Miles');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','John McIntire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Martin Balsam');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Simon Oakland');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('100','Patricia Hitchcock');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('95','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Elijah Wood');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Ian McKellen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Viggo Mortensen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Sean Astin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Sean Bean');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Cate Blanchett');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Hugo Weaving');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Liv Tyler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Ian Holm');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Christopher Lee');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','John Rhys-Davies');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Orlando Bloom');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Dominic Monaghan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Billy boyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Lawrence Makoare');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Craig Parker');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Marton Csokas');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('13','Andy Serkis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('16','Animada');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Robin Wright Penn');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Gary Sinise');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Mykelti Williamson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Sally Field');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Rebecca Williams');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Michael Conner Humphreys');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Harold G. Herthum');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Haley Joel Osment');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','George Kelly');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Bob Penny');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','John Randall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Sam Anderson');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Margo Moorer');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Ione M. Telech');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('1','Christine Seabrook');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Leonardo DiCaprio');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Kate Winslet');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Billy Zane');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Kathy Bates');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Frances Fisher');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Bernard Hill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Jonathan Hyde');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Danny Nucci');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','David Warner');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Bill Paxton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Gloria Stuart');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Victor Garber');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('2','Suzy Amis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Marlon Brando');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Al Pacino');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','James Caan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Robert Duvall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Diane Keaton');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','John Cazale');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Talia Shire');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Richard Castellano');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Sterling Hayden');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Gianni Russo');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Rudy Bond');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','John Marley');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Richard Conte');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Al Lettieri');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Abe Vigoda');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('3','Franco Citti');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Russell Crowe');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Joaquin Phoenix');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Connie Nielsen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Oliver Reed');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Richard Harris');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Derek Jacobi');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Djimon Hounsou');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','David Schofield');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','John Shrapnel');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Tomas Arana');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Ralf Moeller');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Spencer Treat Clark');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','David Hemmings');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Tommy Flanagan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Sven-Ole Thorsen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('4','Tony Curran');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Elijah Wood');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Viggo Mortensen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Ian McKellen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Sean Astin');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Andy Serkis');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','John Rhys-Davies');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Orlando Bloom');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','John Noble');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Miranda Otto');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','David Wenham');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Bernard Hill');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Billy Boyd');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Dominic Monaghan');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Liv Tyler');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Karl Urban');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Ian Holm');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Hugo Weaving');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Cate Blanchett');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('5','Lawrence Makoare');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Christian Bale');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Heath Ledger');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Aaron Eckhart');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Michael Caine');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Gary Oldman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Maggie Gyllenhaal');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Morgan Freeman');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Eric Roberts');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Cillian Murphy');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Anthony Michael Hall');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Michael Jai White');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','William Fichtner');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Edison Chen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Monique Curnen');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Chin Han');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Nestor Carbonell');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Ritchie Coster');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Keith Szarabajka');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Colin McFarlane');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Melinda McGraw');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Nathan Gamble');
Insert into DESAFIO2.REPARTO (IDPELICULA,NOMBREACTOR) values ('6','Michael Vieau');
--------------------------------------------------------
--  Ref Constraints for Table REPARTO
--------------------------------------------------------

  ALTER TABLE "DESAFIO2"."REPARTO" ADD FOREIGN KEY ("IDPELICULA")
	  REFERENCES "DESAFIO2"."PELICULAS" ("ID") ENABLE;
